### PR TITLE
French (France) translation

### PR DESCRIPTION
**Pull request by kevinbioj**
Note: Before merging, I wonder what is the sense of the English string for "help_notime".

### CODE REVIEW

**Comment by 7coil** [comment]
No Time is a useless string that used to exist

It was used for when "uptime" was 0 or falsey

**Comment by kevinbioj** [comment]
Ah ok.
Also replace the "Inviter" at line 39 with "Invitation".
(I can't edit it, I dunno why)

**Comment by 7coil** [comment]
K. Will pull when I get home

**Comment by 7coil** [comment]
Actually I forgot that the help menu also needs translation. This is a file in /promo/help

Sorry

**Comment by 7coil** [comment]
Not help, info

**Comment by WiseMatthack** [comment]
Ah

**Comment by 7coil** [comment]
Did you just create a GitHub account to say "ah"?

Good Job

**Pull request merged**
